/*
 * GcodeParser_cfg.h
 *
 *  Created on: Jun 23, 2021
 *      Author: abdoo
 */

#ifndef GCODEPARSER_CFG_H_
#define GCODEPARSER_CFG_H_

#define GCODEPARSER_MATERIAL_OFFSET_um			100000
#define GCODEPARSER_REVERSE_FEEDRATE			5000

#define GCODEPARSER_TIMER_BASE_PRESCALER		3999
#define GCODEPARSER_HEATING_TIME				10000
#define GCODEPARSER_CUTTING_TIME				10000

#endif /* GCODEPARSER_CFG_H_ */
